# Étape 1 : Build Angular app
FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --output-path=dist

# Étape 2 : Serveur Nginx
FROM nginx:alpine

# Supprimer la config par défaut de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copier les fichiers buildés dans le dossier Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copier une config nginx optionnelle (ex: pour Angular routes)
# COPY nginx.conf /etc/nginx/nginx.conffsf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
